name: CI
on:
  push:
    branches:
      - ci-nimble
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@no-install
    with:
      nimble-version: 4b1112318d06f9a331ed30a94d61685dad423203
      test-command: |
        nimble --lockfile:ci.lock test
