name: CI
on:
  push:
    branches:
      - ci-nimble
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@no-install
    with:
      test-command: |
        nimble test --lockfile:ci.lock
